<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>
    <ItemGroup>
        <Folder Include="Styles\"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Bootstrap.Avalonia.ToolKit\Bootstrap.Avalonia.ToolKit.csproj"/>
    </ItemGroup>
</Project>
